# Generated by Django 5.2.3 on 2025-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('habitacion', '0005_remove_habitacion_descripcion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_booking_per_room_date',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_noches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('habitacion', 'fecha_entrada', 'fecha_salida')},
        ),
    ]
