# Generated by Django 5.2.3 on 2025-06-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_reserva_unique_booking_per_room_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
