# Generated by Django 5.2.3 on 2025-06-20 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_rol', to='usuario.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
