# Generated by Django 5.2.3 on 2025-06-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_piso_servicio_habitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='servicios',
            field=models.ManyToManyField(related_name='habitaciones_con_servicio', to='habitacion.servicio'),
        ),
    ]
