# Generated by Django 5.2.3 on 2025-06-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0003_remove_habitacion_servicio_habitacion_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='descripcion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
