# Generated by Django 5.2.3 on 2025-06-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0004_habitacion_descripcion_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='descripcion',
        ),
    ]
